noinc_simplestorefront_viewbundle:
    resource: "@NoIncSimpleStorefrontViewBundle/Resources/config/routing.yml"
    prefix:   /
    
noinc_simplestorefront_apibundle:
    resource: "@NoIncSimpleStorefrontApiBundle/Controller"
    type:     annotation
    prefix:   '/api'

api_platform:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'
